// <auto-generated />
using System;
using ITShopAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ITShopAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251003074057_AddMore20Products")]
    partial class AddMore20Products
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.33");

            modelBuilder.Entity("ITShopAPI.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("ITShopAPI.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ITShopAPI.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("ITShopAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 10, 3, 14, 40, 57, 655, DateTimeKind.Local).AddTicks(1573),
                            Description = "High-performance laptop for professionals",
                            ImageUrl = "https://via.placeholder.com/300x200?text=Dell+XPS+15",
                            Name = "Laptop Dell XPS 15",
                            Price = 45000m,
                            Stock = 10,
                            UpdatedDate = new DateTime(2025, 10, 3, 14, 40, 57, 655, DateTimeKind.Local).AddTicks(1594)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 10, 3, 14, 40, 57, 655, DateTimeKind.Local).AddTicks(1597),
                            Description = "Latest Apple smartphone with titanium design",
                            ImageUrl = "https://via.placeholder.com/300x200?text=iPhone+15+Pro",
                            Name = "iPhone 15 Pro",
                            Price = 42000m,
                            Stock = 15,
                            UpdatedDate = new DateTime(2025, 10, 3, 14, 40, 57, 655, DateTimeKind.Local).AddTicks(1598)
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 10, 3, 14, 40, 57, 655, DateTimeKind.Local).AddTicks(1600),
                            Description = "Flagship Android smartphone with AI features",
                            ImageUrl = "https://via.placeholder.com/300x200?text=Galaxy+S24",
                            Name = "Samsung Galaxy S24",
                            Price = 35000m,
                            Stock = 20,
                            UpdatedDate = new DateTime(2025, 10, 3, 14, 40, 57, 655, DateTimeKind.Local).AddTicks(1601)
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 10, 3, 14, 40, 57, 655, DateTimeKind.Local).AddTicks(1602),
                            Description = "Ultra-thin laptop with powerful M3 chip",
                            ImageUrl = "https://via.placeholder.com/300x200?text=MacBook+Air",
                            Name = "MacBook Air M3",
                            Price = 48000m,
                            Stock = 8,
                            UpdatedDate = new DateTime(2025, 10, 3, 14, 40, 57, 655, DateTimeKind.Local).AddTicks(1603)
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2025, 10, 3, 14, 40, 57, 655, DateTimeKind.Local).AddTicks(1604),
                            Description = "Professional tablet for creative work",
                            ImageUrl = "https://via.placeholder.com/300x200?text=iPad+Pro",
                            Name = "iPad Pro 12.9",
                            Price = 38000m,
                            Stock = 12,
                            UpdatedDate = new DateTime(2025, 10, 3, 14, 40, 57, 655, DateTimeKind.Local).AddTicks(1605)
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2025, 10, 3, 14, 40, 57, 655, DateTimeKind.Local).AddTicks(1606),
                            Description = "Ultimate gaming laptop with RTX 4090",
                            ImageUrl = "https://via.placeholder.com/300x200?text=ASUS+ROG",
                            Name = "ASUS ROG Strix Gaming Laptop",
                            Price = 75000m,
                            Stock = 5,
                            UpdatedDate = new DateTime(2025, 10, 3, 14, 40, 57, 655, DateTimeKind.Local).AddTicks(1607)
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2025, 10, 3, 14, 40, 57, 655, DateTimeKind.Local).AddTicks(1608),
                            Description = "Premium noise-cancelling wireless headphones",
                            ImageUrl = "https://via.placeholder.com/300x200?text=Sony+WH-1000XM5",
                            Name = "Sony WH-1000XM5 Headphones",
                            Price = 15000m,
                            Stock = 25,
                            UpdatedDate = new DateTime(2025, 10, 3, 14, 40, 57, 655, DateTimeKind.Local).AddTicks(1609)
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2025, 10, 3, 14, 40, 57, 655, DateTimeKind.Local).AddTicks(1610),
                            Description = "Advanced wireless mouse for professionals",
                            ImageUrl = "https://via.placeholder.com/300x200?text=MX+Master+3S",
                            Name = "Logitech MX Master 3S Mouse",
                            Price = 3500m,
                            Stock = 30,
                            UpdatedDate = new DateTime(2025, 10, 3, 14, 40, 57, 655, DateTimeKind.Local).AddTicks(1611)
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2025, 10, 3, 14, 40, 57, 655, DateTimeKind.Local).AddTicks(1612),
                            Description = "Latest smartwatch with advanced health features",
                            ImageUrl = "https://via.placeholder.com/300x200?text=Apple+Watch+9",
                            Name = "Apple Watch Series 9",
                            Price = 18000m,
                            Stock = 18,
                            UpdatedDate = new DateTime(2025, 10, 3, 14, 40, 57, 655, DateTimeKind.Local).AddTicks(1613)
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2025, 10, 3, 14, 40, 57, 655, DateTimeKind.Local).AddTicks(1615),
                            Description = "Ultra HD monitor for professional work",
                            ImageUrl = "https://via.placeholder.com/300x200?text=Samsung+4K+32",
                            Name = "Samsung 4K Monitor 32 inch",
                            Price = 22000m,
                            Stock = 12,
                            UpdatedDate = new DateTime(2025, 10, 3, 14, 40, 57, 655, DateTimeKind.Local).AddTicks(1615)
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2025, 10, 3, 14, 40, 57, 655, DateTimeKind.Local).AddTicks(1616),
                            Description = "Mechanical gaming keyboard with RGB",
                            ImageUrl = "https://via.placeholder.com/300x200?text=Razer+BlackWidow",
                            Name = "Razer BlackWidow V3 Keyboard",
                            Price = 5500m,
                            Stock = 22,
                            UpdatedDate = new DateTime(2025, 10, 3, 14, 40, 57, 655, DateTimeKind.Local).AddTicks(1617)
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2025, 10, 3, 14, 40, 57, 655, DateTimeKind.Local).AddTicks(1618),
                            Description = "Portable external hard drive",
                            ImageUrl = "https://via.placeholder.com/300x200?text=WD+Passport+2TB",
                            Name = "WD My Passport 2TB External HDD",
                            Price = 2800m,
                            Stock = 40,
                            UpdatedDate = new DateTime(2025, 10, 3, 14, 40, 57, 655, DateTimeKind.Local).AddTicks(1619)
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2025, 10, 3, 14, 40, 57, 655, DateTimeKind.Local).AddTicks(1620),
                            Description = "Active noise cancellation wireless earbuds",
                            ImageUrl = "https://via.placeholder.com/300x200?text=AirPods+Pro+2",
                            Name = "AirPods Pro 2nd Gen",
                            Price = 9500m,
                            Stock = 28,
                            UpdatedDate = new DateTime(2025, 10, 3, 14, 40, 57, 655, DateTimeKind.Local).AddTicks(1621)
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2025, 10, 3, 14, 40, 57, 655, DateTimeKind.Local).AddTicks(1622),
                            Description = "Affordable fitness tracker smartband",
                            ImageUrl = "https://via.placeholder.com/300x200?text=Mi+Band+8",
                            Name = "Xiaomi Mi Band 8",
                            Price = 1200m,
                            Stock = 50,
                            UpdatedDate = new DateTime(2025, 10, 3, 14, 40, 57, 655, DateTimeKind.Local).AddTicks(1622)
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2025, 10, 3, 14, 40, 57, 655, DateTimeKind.Local).AddTicks(1624),
                            Description = "Professional mirrorless camera",
                            ImageUrl = "https://via.placeholder.com/300x200?text=Canon+EOS+R6",
                            Name = "Canon EOS R6 Camera",
                            Price = 95000m,
                            Stock = 6,
                            UpdatedDate = new DateTime(2025, 10, 3, 14, 40, 57, 655, DateTimeKind.Local).AddTicks(1624)
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2025, 10, 3, 14, 40, 57, 655, DateTimeKind.Local).AddTicks(1625),
                            Description = "Compact drone with 4K camera",
                            ImageUrl = "https://via.placeholder.com/300x200?text=DJI+Mini+3",
                            Name = "DJI Mini 3 Pro Drone",
                            Price = 28000m,
                            Stock = 10,
                            UpdatedDate = new DateTime(2025, 10, 3, 14, 40, 57, 655, DateTimeKind.Local).AddTicks(1626)
                        },
                        new
                        {
                            Id = 17,
                            CreatedDate = new DateTime(2025, 10, 3, 14, 40, 57, 655, DateTimeKind.Local).AddTicks(1628),
                            Description = "Action camera with 5.3K video",
                            ImageUrl = "https://via.placeholder.com/300x200?text=GoPro+Hero+12",
                            Name = "GoPro Hero 12",
                            Price = 18500m,
                            Stock = 15,
                            UpdatedDate = new DateTime(2025, 10, 3, 14, 40, 57, 655, DateTimeKind.Local).AddTicks(1628)
                        },
                        new
                        {
                            Id = 18,
                            CreatedDate = new DateTime(2025, 10, 3, 14, 40, 57, 655, DateTimeKind.Local).AddTicks(1630),
                            Description = "Gaming console with vibrant OLED screen",
                            ImageUrl = "https://via.placeholder.com/300x200?text=Switch+OLED",
                            Name = "Nintendo Switch OLED",
                            Price = 12500m,
                            Stock = 20,
                            UpdatedDate = new DateTime(2025, 10, 3, 14, 40, 57, 655, DateTimeKind.Local).AddTicks(1631)
                        },
                        new
                        {
                            Id = 19,
                            CreatedDate = new DateTime(2025, 10, 3, 14, 40, 57, 655, DateTimeKind.Local).AddTicks(1632),
                            Description = "Next-gen gaming console",
                            ImageUrl = "https://via.placeholder.com/300x200?text=PlayStation+5",
                            Name = "PlayStation 5",
                            Price = 19900m,
                            Stock = 8,
                            UpdatedDate = new DateTime(2025, 10, 3, 14, 40, 57, 655, DateTimeKind.Local).AddTicks(1633)
                        },
                        new
                        {
                            Id = 20,
                            CreatedDate = new DateTime(2025, 10, 3, 14, 40, 57, 655, DateTimeKind.Local).AddTicks(1634),
                            Description = "Powerful gaming console with 4K support",
                            ImageUrl = "https://via.placeholder.com/300x200?text=Xbox+Series+X",
                            Name = "Xbox Series X",
                            Price = 18500m,
                            Stock = 12,
                            UpdatedDate = new DateTime(2025, 10, 3, 14, 40, 57, 655, DateTimeKind.Local).AddTicks(1635)
                        });
                });

            modelBuilder.Entity("ITShopAPI.Models.Order", b =>
                {
                    b.HasOne("ITShopAPI.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ITShopAPI.Models.OrderItem", b =>
                {
                    b.HasOne("ITShopAPI.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITShopAPI.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ITShopAPI.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("ITShopAPI.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("ITShopAPI.Models.Product", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
