// <auto-generated />
using System;
using ITShopAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ITShopAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251003080847_AddPerformanceIndexes")]
    partial class AddPerformanceIndexes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.33");

            modelBuilder.Entity("ITShopAPI.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("ITShopAPI.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PaymentStatus");

                    b.HasIndex("Status");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ITShopAPI.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("ITShopAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Price");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 10, 3, 15, 8, 46, 916, DateTimeKind.Local).AddTicks(519),
                            Description = "High-performance laptop for professionals",
                            ImageUrl = "https://placehold.co/300x200/1890ff/white?text=Dell+XPS+15",
                            Name = "Laptop Dell XPS 15",
                            Price = 45000m,
                            Stock = 10,
                            UpdatedDate = new DateTime(2025, 10, 3, 15, 8, 46, 916, DateTimeKind.Local).AddTicks(531)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 10, 3, 15, 8, 46, 916, DateTimeKind.Local).AddTicks(533),
                            Description = "Latest Apple smartphone with titanium design",
                            ImageUrl = "https://placehold.co/300x200/52c41a/white?text=iPhone+15+Pro",
                            Name = "iPhone 15 Pro",
                            Price = 42000m,
                            Stock = 15,
                            UpdatedDate = new DateTime(2025, 10, 3, 15, 8, 46, 916, DateTimeKind.Local).AddTicks(534)
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 10, 3, 15, 8, 46, 916, DateTimeKind.Local).AddTicks(535),
                            Description = "Flagship Android smartphone with AI features",
                            ImageUrl = "https://placehold.co/300x200/722ed1/white?text=Galaxy+S24",
                            Name = "Samsung Galaxy S24",
                            Price = 35000m,
                            Stock = 20,
                            UpdatedDate = new DateTime(2025, 10, 3, 15, 8, 46, 916, DateTimeKind.Local).AddTicks(535)
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 10, 3, 15, 8, 46, 916, DateTimeKind.Local).AddTicks(536),
                            Description = "Ultra-thin laptop with powerful M3 chip",
                            ImageUrl = "https://placehold.co/300x200/fa8c16/white?text=MacBook+Air",
                            Name = "MacBook Air M3",
                            Price = 48000m,
                            Stock = 8,
                            UpdatedDate = new DateTime(2025, 10, 3, 15, 8, 46, 916, DateTimeKind.Local).AddTicks(537)
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2025, 10, 3, 15, 8, 46, 916, DateTimeKind.Local).AddTicks(538),
                            Description = "Professional tablet for creative work",
                            ImageUrl = "https://placehold.co/300x200/eb2f96/white?text=iPad+Pro",
                            Name = "iPad Pro 12.9",
                            Price = 38000m,
                            Stock = 12,
                            UpdatedDate = new DateTime(2025, 10, 3, 15, 8, 46, 916, DateTimeKind.Local).AddTicks(538)
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2025, 10, 3, 15, 8, 46, 916, DateTimeKind.Local).AddTicks(539),
                            Description = "Ultimate gaming laptop with RTX 4090",
                            ImageUrl = "https://placehold.co/300x200/13c2c2/white?text=ASUS+ROG",
                            Name = "ASUS ROG Strix Gaming Laptop",
                            Price = 75000m,
                            Stock = 5,
                            UpdatedDate = new DateTime(2025, 10, 3, 15, 8, 46, 916, DateTimeKind.Local).AddTicks(540)
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2025, 10, 3, 15, 8, 46, 916, DateTimeKind.Local).AddTicks(541),
                            Description = "Premium noise-cancelling wireless headphones",
                            ImageUrl = "https://placehold.co/300x200/2f54eb/white?text=Sony+WH-1000XM5",
                            Name = "Sony WH-1000XM5 Headphones",
                            Price = 15000m,
                            Stock = 25,
                            UpdatedDate = new DateTime(2025, 10, 3, 15, 8, 46, 916, DateTimeKind.Local).AddTicks(541)
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2025, 10, 3, 15, 8, 46, 916, DateTimeKind.Local).AddTicks(542),
                            Description = "Advanced wireless mouse for professionals",
                            ImageUrl = "https://placehold.co/300x200/a0d911/white?text=MX+Master+3S",
                            Name = "Logitech MX Master 3S Mouse",
                            Price = 3500m,
                            Stock = 30,
                            UpdatedDate = new DateTime(2025, 10, 3, 15, 8, 46, 916, DateTimeKind.Local).AddTicks(543)
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2025, 10, 3, 15, 8, 46, 916, DateTimeKind.Local).AddTicks(543),
                            Description = "Latest smartwatch with advanced health features",
                            ImageUrl = "https://placehold.co/300x200/f5222d/white?text=Apple+Watch+9",
                            Name = "Apple Watch Series 9",
                            Price = 18000m,
                            Stock = 18,
                            UpdatedDate = new DateTime(2025, 10, 3, 15, 8, 46, 916, DateTimeKind.Local).AddTicks(544)
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2025, 10, 3, 15, 8, 46, 916, DateTimeKind.Local).AddTicks(545),
                            Description = "Ultra HD monitor for professional work",
                            ImageUrl = "https://placehold.co/300x200/1890ff/white?text=Samsung+4K+32",
                            Name = "Samsung 4K Monitor 32 inch",
                            Price = 22000m,
                            Stock = 12,
                            UpdatedDate = new DateTime(2025, 10, 3, 15, 8, 46, 916, DateTimeKind.Local).AddTicks(545)
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2025, 10, 3, 15, 8, 46, 916, DateTimeKind.Local).AddTicks(546),
                            Description = "Mechanical gaming keyboard with RGB",
                            ImageUrl = "https://placehold.co/300x200/52c41a/white?text=Razer+BlackWidow",
                            Name = "Razer BlackWidow V3 Keyboard",
                            Price = 5500m,
                            Stock = 22,
                            UpdatedDate = new DateTime(2025, 10, 3, 15, 8, 46, 916, DateTimeKind.Local).AddTicks(547)
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2025, 10, 3, 15, 8, 46, 916, DateTimeKind.Local).AddTicks(548),
                            Description = "Portable external hard drive",
                            ImageUrl = "https://placehold.co/300x200/722ed1/white?text=WD+Passport+2TB",
                            Name = "WD My Passport 2TB External HDD",
                            Price = 2800m,
                            Stock = 40,
                            UpdatedDate = new DateTime(2025, 10, 3, 15, 8, 46, 916, DateTimeKind.Local).AddTicks(548)
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2025, 10, 3, 15, 8, 46, 916, DateTimeKind.Local).AddTicks(549),
                            Description = "Active noise cancellation wireless earbuds",
                            ImageUrl = "https://placehold.co/300x200/fa8c16/white?text=AirPods+Pro+2",
                            Name = "AirPods Pro 2nd Gen",
                            Price = 9500m,
                            Stock = 28,
                            UpdatedDate = new DateTime(2025, 10, 3, 15, 8, 46, 916, DateTimeKind.Local).AddTicks(549)
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2025, 10, 3, 15, 8, 46, 916, DateTimeKind.Local).AddTicks(550),
                            Description = "Affordable fitness tracker smartband",
                            ImageUrl = "https://placehold.co/300x200/eb2f96/white?text=Mi+Band+8",
                            Name = "Xiaomi Mi Band 8",
                            Price = 1200m,
                            Stock = 50,
                            UpdatedDate = new DateTime(2025, 10, 3, 15, 8, 46, 916, DateTimeKind.Local).AddTicks(551)
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2025, 10, 3, 15, 8, 46, 916, DateTimeKind.Local).AddTicks(552),
                            Description = "Professional mirrorless camera",
                            ImageUrl = "https://placehold.co/300x200/13c2c2/white?text=Canon+EOS+R6",
                            Name = "Canon EOS R6 Camera",
                            Price = 95000m,
                            Stock = 6,
                            UpdatedDate = new DateTime(2025, 10, 3, 15, 8, 46, 916, DateTimeKind.Local).AddTicks(552)
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2025, 10, 3, 15, 8, 46, 916, DateTimeKind.Local).AddTicks(585),
                            Description = "Compact drone with 4K camera",
                            ImageUrl = "https://placehold.co/300x200/2f54eb/white?text=DJI+Mini+3",
                            Name = "DJI Mini 3 Pro Drone",
                            Price = 28000m,
                            Stock = 10,
                            UpdatedDate = new DateTime(2025, 10, 3, 15, 8, 46, 916, DateTimeKind.Local).AddTicks(586)
                        },
                        new
                        {
                            Id = 17,
                            CreatedDate = new DateTime(2025, 10, 3, 15, 8, 46, 916, DateTimeKind.Local).AddTicks(587),
                            Description = "Action camera with 5.3K video",
                            ImageUrl = "https://placehold.co/300x200/a0d911/white?text=GoPro+Hero+12",
                            Name = "GoPro Hero 12",
                            Price = 18500m,
                            Stock = 15,
                            UpdatedDate = new DateTime(2025, 10, 3, 15, 8, 46, 916, DateTimeKind.Local).AddTicks(587)
                        },
                        new
                        {
                            Id = 18,
                            CreatedDate = new DateTime(2025, 10, 3, 15, 8, 46, 916, DateTimeKind.Local).AddTicks(588),
                            Description = "Gaming console with vibrant OLED screen",
                            ImageUrl = "https://placehold.co/300x200/f5222d/white?text=Switch+OLED",
                            Name = "Nintendo Switch OLED",
                            Price = 12500m,
                            Stock = 20,
                            UpdatedDate = new DateTime(2025, 10, 3, 15, 8, 46, 916, DateTimeKind.Local).AddTicks(589)
                        },
                        new
                        {
                            Id = 19,
                            CreatedDate = new DateTime(2025, 10, 3, 15, 8, 46, 916, DateTimeKind.Local).AddTicks(590),
                            Description = "Next-gen gaming console",
                            ImageUrl = "https://placehold.co/300x200/1890ff/white?text=PlayStation+5",
                            Name = "PlayStation 5",
                            Price = 19900m,
                            Stock = 8,
                            UpdatedDate = new DateTime(2025, 10, 3, 15, 8, 46, 916, DateTimeKind.Local).AddTicks(590)
                        },
                        new
                        {
                            Id = 20,
                            CreatedDate = new DateTime(2025, 10, 3, 15, 8, 46, 916, DateTimeKind.Local).AddTicks(591),
                            Description = "Powerful gaming console with 4K support",
                            ImageUrl = "https://placehold.co/300x200/52c41a/white?text=Xbox+Series+X",
                            Name = "Xbox Series X",
                            Price = 18500m,
                            Stock = 12,
                            UpdatedDate = new DateTime(2025, 10, 3, 15, 8, 46, 916, DateTimeKind.Local).AddTicks(591)
                        });
                });

            modelBuilder.Entity("ITShopAPI.Models.Order", b =>
                {
                    b.HasOne("ITShopAPI.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ITShopAPI.Models.OrderItem", b =>
                {
                    b.HasOne("ITShopAPI.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITShopAPI.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ITShopAPI.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("ITShopAPI.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("ITShopAPI.Models.Product", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
